language: ruby
cache: bundler
addons:
  ssh_known_hosts: $DEPLOY_HOST
before_install:
- gem install bundler
bundler_args: ""
script:
- ls
rvm:
- 2.6.5
gemfile:
- Gemfile
branches:
  only:
  - dev
after_success:
- mkdir -p tmp/.ssh
- openssl enc -aes-256-cbc -d -in deploy_rsa.enc -out tmp/.ssh/terraling-travis.pem -k $ENC_PASS
- chmod 700 tmp/.ssh/
- chmod 600 tmp/.ssh/terraling-travis.pem
- eval "$(ssh-agent -s)"
- ssh-add tmp/.ssh/terraling-travis.pem
- RAILS_ENV=production bundle exec cap deploy
